#!/bin/bash
#
# Get download URLs from dafont.com.

for page in {1..20}; do
  curl -s "http://www.dafont.com/top.php?page=$page" | grep 'http://dl.dafont.com/dl' |
    sed -E $'s/href="/\\\n/g' | grep -E '^http:\/\/dl.dafont.com\/dl\/\?f=' |
    sed -E 's/".*$//g'
done
