#!/bin/bash
#
# Read dafont download URLs from stdin and download them
# to the specified directory.

if [ $# -ne 1 ]; then
  echo 'Usage: dafont_dl <out_dir>' >&2
  exit 1
fi

if [ ! -d "$1" ]; then
  echo "bad output directory: $1" >&2
  exit 1
fi

cd "$1"

while read url
do
  echo "Fetching $url"
  curl -s $url >temp.zip
  unzip -qq -d temp_unzipped temp.zip
  mv temp_unzipped/*.ttf . 2>/dev/null
  rm -rf temp_unzipped/ temp.zip
done
