#!/bin/bash
#
# Render a TTF file as character images.

if [ $# -ne 2 ]; then
  echo 'Usage: ttf_render <font.ttf> <out_dir>' >&2
  exit 1
fi

if [ ! -d "$2" ]; then
  echo "bad output directory: $2" >&2
  exit 1
fi

make_font_image() {
  convert -size 54x54 \
    -font "$1" -pointsize 42 \
    -fill black \
    -background transparent \
    -gravity center \
    caption:$2 \
    "$3/$2.png"
}

mkdir "$2/lowercase"
for ch in {a..z}
do
  make_font_image "$1" $ch "$2/lowercase"
done

mkdir "$2/uppercase"
for ch in {A..Z}
do
  make_font_image "$1" $ch "$2/uppercase"
done

mkdir "$2/digits"
for ch in {0..9}
do
  make_font_image "$1" $ch "$2/digits"
done

# If the font does not support digits, every digit
# file will look the same (usually a question mark).
comparison=$(compare -metric phash "$2/digits/2.png" "$2/digits/4.png" /dev/null 2>&1)
if [ "$comparison" = 0 ]; then
  rm -r "$2/digits"
fi
